DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS
(
    ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(255)
);
CREATE TABLE GENRES
(
    ID         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GENRE_NAME VARCHAR(255)
);
CREATE TABLE BOOKS
(
    ID        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID INT REFERENCES AUTHORS (ID),
    GENRE_ID  INT REFERENCES GENRES (ID),
    BOOK_NAME VARCHAR(255)
);

