management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, logfile, metrics
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: when_authorized
    logfile:
      enabled: true
      external-file: logLibrary.log
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  messages:
    encoding: UTF-8
    basename: messages
logging:
  file:
    name: logLibrary.log

