spring:
  data:
    mongodb:
      database: libraryBooks
      port: 27017
      host: localhost
  main:
    allow-circular-references: true
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.spring.mongock.changelog
  enabled: true
  index-creation: true
