spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: backupdb
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  messages:
    encoding: UTF-8
    basename: messages
  batch:
    job:
      enabled: false


