management:
  endpoints.web.exposure.include: "*"
  endpoint.health:
    enabled: true
    show-details: always
    show-components: when_authorized
  health:
    circuitbreakers.enabled: true
    readinessstate.enabled: true
    ratelimiters.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10 # размер раздвижного окна
      minimumNumberOfCalls: 3 # минимальное количество звонков, неудач
      permittedNumberOfCallsInHalfOpenState: 3 # разрешенное-количество-вызовов-в-полуоткрытом-состоянии
      automaticTransitionFromOpenToHalfOpenEnabled: true # включен автоматический переход от открытого к полуоткрытому
      waitDurationInOpenState: 5s # продолжительность ожидания в открытом состоянии
      failureRateThreshold: 50 # порог частоты отказов %
      eventConsumerBufferSize: 10
      recordExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException
        - java.util.concurrent.TimeoutException
      ignoreExceptions:
        - java.lang.RuntimeException
  instances:
    AuthorFindAll:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 2s
      retryExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException
        - java.util.concurrent.TimeoutException
      ignoreExceptions:
        - java.lang.RuntimeException
  instances:
    AuthorFindAll:
      baseConfig: default
  metrics:
    legacy:
      enabled: true

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 1s
  instances:
    AuthorFindAll:
      base-config: default
  metrics:
      enabled: true


spring:
  application:
    name: My library
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  messages:
    encoding: UTF-8
    basename: messages


