management:
  endpoints.web.exposure.include: health
  endpoint.health:
    enabled: true
    show-details: always
    show-components: when_authorized
  health:
    circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      sliding-window-size: 10 # размер раздвижного окна
      minimum-number-of-calls: 3 # минимальное количество звонков, неудач
      slow-call-duration-threshold: 200
      failure-rate-threshold: 50 # порог частоты отказов %
      ignore-exceptions:
        - java.lang.RuntimeException
  instances:
    AuthorFindAll:
      base-config: default
    AuthorFindOne:
      base-config: default
    GenreFindAll:
      base-config: default
    GenreFindOne:
      base-config: default
    BookFindAll:
      base-config: default
    BookFindOne:
      base-config: default

spring:
  application:
    name: My library
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  messages:
    encoding: UTF-8
    basename: messages


