DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY, AUTHOR_NAME VARCHAR(255));
CREATE TABLE BOOKS(ID INT PRIMARY KEY, AUTHOR_ID INT, GENRE_ID INT, BOOK_NAME VARCHAR(255));
CREATE TABLE GENRES(ID INT PRIMARY KEY, GENRE_NAME VARCHAR(255));
